In [ ]:
# prompt: install tensorflow

!pip install tensorflow


In [1]:
# !pip install tensorflow
import tensorflow as tf


In [2]:
con1 = tf.constant([[3,4],[4,5]])
con2 = tf.constant(3.45)
con3 = tf.constant("Spartaa!!")
con4 = tf.constant(False)

In [4]:
# prompt: print the above in seperate lines

print(con1)
print(con2)
print(con3)
print(con4)


tf.Tensor(
[[3 4]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(3.45, shape=(), dtype=float32)
tf.Tensor(b'Spartaa!!', shape=(), dtype=string)
tf.Tensor(False, shape=(), dtype=bool)


In [6]:
Addition = tf.constant(50) + tf.constant(10)
Multiplication = tf.constant(20) * tf.constant(20)

In [7]:
print(Addition)

tf.Tensor(60, shape=(), dtype=int32)


In [8]:
print(Multiplication)

tf.Tensor(400, shape=(), dtype=int32)


In [9]:
Addition = tf.constant([1,2,3,4,5]) + tf.constant([5,4,3,2,1])
Multiplication = tf.constant([1,2,3,4,5]) * tf.constant([5,4,3,2,1])

In [10]:
print(Addition,Multiplication)

tf.Tensor([6 6 6 6 6], shape=(5,), dtype=int32) tf.Tensor([5 8 9 8 5], shape=(5,), dtype=int32)


In [12]:
str1 = tf.constant("I love")
str2 = tf.constant(" TensorFlow")

In [13]:
print(str1+str2)

tf.Tensor(b'I love TensorFlow', shape=(), dtype=string)


In [16]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()

In [21]:
str1 = tf.constant("I love")
str2 = tf.constant(" TensorFlow")
str3 = tf.constant(" Keras")
y = str1+str2
z = y+str3

In [22]:
z

<tf.Tensor 'add_5:0' shape=() dtype=string>

In [13]:
sum = 10+20
sum

30

In [24]:
# prompt: use the above to print different names

# Create a TensorFlow session
sess = tf.compat.v1.Session()

# Define the placeholder for the name
str_name = tf.compat.v1.placeholder(tf.string)

# Define the operation to concatenate "I am" with the name
name1 = "I am " + str_name

# Run the session with different names
print(sess.run(name1, feed_dict={str_name: "Alice"}))
print(sess.run(name1, feed_dict={str_name: "Bob"}))
print(sess.run(name1, feed_dict={str_name: "Charlie"}))

# Close the session
sess.close()


b'I am Alice'
b'I am Bob'
b'I am Charlie'


In [26]:
# creating a placeholder
a = tf.placeholder(tf.float32, None)

# creating an operation
b = a + 10

# creating a session
with tf.Session() as session:

    # feeding data in the placeholder
    operation_res = session.run(b, feed_dict={a: [10, 20, 30, 40]})
    print("after executing the operation: " + str(operation_res))

after executing the operation: [20. 30. 40. 50.]
