In [2]:
pip install numpy

In [3]:
import numpy as np
arr_num1=np.array([[[12,23,34],[12,23,45],[7,8,9]]])
print(arr_num1.shape)
print(arr_num1.ndim)
print(arr_num1.dtype)
print(arr_num1.size)#row*col
# (1, 3, 3)
# 3
# int64
# 9

(1, 3, 3)
3
int64
9


#creating numpy array

In [4]:
np.zeros((2,3))
np.ones((2,3))
np.eye(3)
np.arange(0,10)
np.arange(0,10,2)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

math compute

In [5]:
arr_math=np.array([1,2,3,4,5])
print("sum",arr_math.sum() )
print("variance",np.var(arr_math,axis=0))
print("mean",arr_math.mean())
print("max & min",arr_math.max(),arr_math.min())
print("nan check",np.isnan(arr_math))

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Perform element-wise operations
result_addition= array1 + array2
result_subtract = array1 - array2
result_multiply = array1 * array2
result_divide = array1 / array2
result_power = np.power(array1, 2)

sum 15
mean 3.0
max & min 5 1


extracting part of array

In [23]:
arr_initial=np.array([11,22,33,44,55,66,77,88,99])
print(arr_initial[1:3])
print(arr_initial[1::2])
print(arr_initial[::-1])
arr_first_half=arr_initial[:int(arr_initial.size/2)][::-1]
arr_second_half=arr_initial[int(arr_initial.size/2):][::-2]


arr_multid=np.array([[1, 2,12,12], [3, 4,3,4],[33,45,5,6],[78,705,8,0]])
#arr_multid[row_slice,col_slice,gapper]
arr_multid[:,1:3]#it goes till n-1


#conditional slicing
arr_initial_new=arr_initial[arr_initial>50]
print(arr_initial_new)
arr_initial_new=arr_initial[arr_initial%2==0]
print(arr_initial_new)

[22 33]
[22 44 66 88]
[99 88 77 66 55 44 33 22 11]
[55 66 77 88 99]
[22 44 66 88]


code friendly funcs:::

In [35]:
import numpy as np

# ... (previous code)
print("original arr",arr_initial)
print("unique element of array",np.unique(arr_initial))
print("sorted array",np.sort(arr_initial))
print("sorted in the array index",np.argsort(arr_initial))
print("conditional validated",np.where(arr_initial>54,1,0))
print("cumalative sum",np.cumsum(arr_initial))
print("randomnumber array ", np.random.randint(0, 10, (3, 3)))
#start ,end , shape
print("product in array",np.dot(arr_initial,arr_initial))
print(arr_first_half@arr_first_half)
print("concate join array",np.concatenate([arr_first_half,arr_first_half],axis=0))

arr_first_half_2d = arr_first_half.reshape(1, -1)

# Removed the [:-1] slicing to ensure both arrays have the same number of columns after reshaping
arr_second_half_2d = arr_second_half.reshape(1, -1)
print("first reshaped array",arr_first_half_2d)
print("second reshaped array",arr_second_half_2d)
print("new concated array",np.concatenate([arr_first_half_2d,arr_second_half_2d],axis=1))

# Pad arr_second_half_2d to match the number of columns in arr_first_half_2d for vstack
# Pad on the right (mode='constant', pad_width=((0, 0), (0, number_of_columns_to_add)))
# The number of columns to add is the difference between the shapes along axis 1
pad_width = arr_first_half_2d.shape[1] - arr_second_half_2d.shape[1]
arr_second_half_2d_padded = np.pad(arr_second_half_2d, ((0, 0), (0, pad_width)), mode='constant', constant_values=0) # Pad with zeros

# Now vstack will work as both arrays have the same number of columns
print("vertically joined arr",np.vstack([arr_first_half_2d, arr_second_half_2d_padded]))#row instance is added

print("horizontaly joined arr",np.hstack([arr_first_half_2d,arr_second_half_2d]))#col size len increases

original arr [11 22 33 44 55 66 77 88 99]
unique element of array [11 22 33 44 55 66 77 88 99]
sorted array [11 22 33 44 55 66 77 88 99]
sorted in the array index [0 1 2 3 4 5 6 7 8]
conditional validated [0 0 0 0 1 1 1 1 1]
cumalative sum [ 11  33  66 110 165 231 308 396 495]
randomnumber array  [[0 5 4]
 [2 6 6]
 [3 1 8]]
product in array 34485
concate join array [44 33 22 11 44 33 22 11]
first reshaped array [[44 33 22 11]]
second reshaped array [[99 77 55]]
new concated array [[44 33 22 11 99 77 55]]
vertically joined arr [[44 33 22 11]
 [99 77 55  0]]
horizontaly joined arr [[44 33 22 11 99 77 55]]


In [36]:
# Create a multidimensional array
multidimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use the flatten() method to convert it to a 1D array
one_dimensional_array = multidimensional_array.flatten()

compare two array


In [37]:
np.array_equal(arr_math, arr_initial)

False

remove null values

In [38]:
import numpy as np

# Create a NumPy array with missing values (NaN)
arr = np.array([1.0, 2.0, np.nan, 4.0, 5.0])

# Create a masked array where missing values are masked
masked_arr = np.ma.masked_invalid(arr)

# Access only non-missing values
clean_data = masked_arr.compressed()

print(clean_data)

[1. 2. 4. 5.]


no of occurance of each ele

In [40]:
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
np.bincount(arr)#[countof 0 , couuntof 1...]

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])

unique ele , n count of ele

In [41]:
import numpy as np
array = np.array([1, 2, 3, 1, 2, 3, 3, 4, 5, 6, 7, 5])
unique, counts = np.unique(array, return_counts=True)
print(unique)
print(counts)

[1 2 3 4 5 6 7]
[2 2 3 1 2 1 1]


split in given parts

In [43]:
import numpy as np
arr = np.arange(5.0)
split_arrs = np.array_split(arr, 7)
split_arrs

[array([0.]),
 array([1.]),
 array([2.]),
 array([3.]),
 array([4.]),
 array([], dtype=float64),
 array([], dtype=float64)]

Question Hunt !!!


1 .difference between arr.size vs arr.shape
2. why use numpy if i have array
3. how to create identity matricx
4. linspace vs arange


5. shallow copy vs deep copy
6. random().randint() vs seed()
7. universal functions ?/
8. numpy faster than list why?
9. normalisation technique used to normailse nupy array

10. np.mean() method calculates the arithmetic mean and provides additional   options for input and results. For example, it has the option to specify  what data types have to be taken, where the result has to be placed etc.
11. np.average() computes the weighted average if the weights parameter is  specified. In the case of weighted average, instead of considering that  each data point is contributing equally to the final average, it considers that some data points have more weightage than the others (unequal contribution)

12. broadcast vs vectorisation  
13. memmap==>memory optimisation
14. numpy multicore ?why 



In [ ]:
df[‘student_cat’] = np.where(df[‘score’] > 80, ‘good’, ‘bad’)

In [ ]:
#create a window of size 3 for through out array
import numpy as np

from numpy.lib.stride_tricks import sliding_window_view
x = np.arange(6)
v = sliding_window_view(x, 3)

In [ ]:
import numpy as np

array = np.array([[10, 15, 20, 25],
                  [30, 35, 40, 45],
                  [50, 55, 60, 65]])
condition = array > 30
filtered_elements = array[condition]
print(filtered_elements)  
print(condition)

In [ ]:
import numpy as np

# Create a 2D array
data = np.array([
    [1, 2, 3, 4, 5],
    [10, 15, 20, 25, 30],
    [100, 200, 300, 400, 500]
])

#find the max from each row -min from each row  
def diffmaxmin(arr):
    return np.max(arr)-np.min(arr)

#for each row i need to do the func diffmaxmin 
answer=np.apply_along_axis(diffmaxmin,axis=1,arr=data)
print("the row wise maxmindiff",answer)

In [ ]:
import numpy as np

# Create a 2D array
data = np.array([
    [1, 2, 3, 4, 5],
    [10, 15, 20, 25, 30],
    [100, 200, 300, 400, 500]
])
answer=np.apply(lambda ele:ele%2, data)
print(answer)
#this is wrong 
#.apply() is a method used in Pandas, not NumPy

#use vectorised code 
import numpy as np

# Create a 2D array
data = np.array([
    [1, 2, 3, 4, 5],
    [10, 15, 20, 25, 30],
    [100, 200, 300, 400, 500]
])

# Element-wise modulus operation
answer = data % 2

print(answer)


In [ ]:
import numpy as np

# Create a 2D array
data = np.array([
    [1, 2, 3, 4, 5],
    [10, 15, 20, 25, 30],
    [100, 200, 300, 400, 500]
])
answer=np.apply_along_axis(lambda ele:ele+2,axis=1 , arr=data)
print(answer)
# [[  3   4   5   6   7]
#  [ 12  17  22  27  32]
#  [102 202 302 402 502]]

In [ ]:
#generate the dataset using numpy
import numpy as np

# Generate a sample dataset
np.random.seed(42)  # For reproducibility
data = np.vstack([
    np.random.normal(loc=[1, 1], scale=0.5, size=(50, 2)),
    np.random.normal(loc=[5, 5], scale=0.5, size=(50, 2)),
    np.random.normal(loc=[9, 1], scale=0.5, size=(50, 2))
])

In [ ]:
#reverse a multi d array 
array = np.array([[1, 2, 3], [4, 5, 6]])
flipped = np.flip(array)
print(array)

In [ ]:
#create a diagonal matrix 
arr3 = np.diag([1,2,3,4])

In [ ]:
# arr[:0] vs 
# arr[:,[0]]
#meshgrid 


In [ ]:
def moved_avg(arr,n=3):
    cumsum=np.cumsum(arr)
    cumsum[n:]=cumsum[n:]-cumsum[:-n]
    return cumsum[n-1:]/n